### ISSUE TITLE
Acquiring Abstracts For AHRQ Clinical Guidelines

### ISSUE THREAD

**Issue by chackoge** [NETESOLUTIONS/PARDI_ClnGdlns#43]
The present web-scrape returns Silverchair IDs, Title, URLs from the current inventory of clinical guidelines at the National Clinical Guideline Clearinghouse (AHRQ). These data are processed and made available with associated data (cited references and grants) through an internal NIH website. At present, the titles of clinical guidelines are searched. It would be valuable to acquire the abstracts of these clinical guidelines and index them to support better searching.

**Comment by chackoge** [comment]
Could we get an update on the status of this issue?

**Comment by sammathography** [comment]
This issue is closed. Abstract generating scripts is written and embedded into weekly update process. The algorithm makes use of the both eUtils API and the Web of Science data.
