### ISSUE TITLE
PDF shredding, citation parsing, and citation matching

### ISSUE THREAD

**Issue by chackoge** [NETESOLUTIONS/PARDI_ClnGdlns#44]
Roughly a third of the AHRQ current inventory of clinical guidelines is published in PubMed. The remaining 2/3 is less accessible to the PARDI team because of the inability to conduct PMID-WoSID exercises. We need to get pdf documents for as many of the remaining clinical guidelines, extract references and find pmids and/or WoSIDs for them.

**Comment by chackoge** [comment]
This project should be considered background for now while we work on Q1 milestones.

**Comment by sammathography** [comment]
Sure. This project requires a lot of time. We should divide these project into smaller tasks, and distribute them over the consecutive sprints as a background task.

**Comment by chackoge** [comment]
Deferred to a later date on account of competing priorities
